# Generated by Django 5.2.4 on 2025-07-07 17:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(default='')),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=11)),
                ('creation_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('finish_datetime', models.DateTimeField(blank=True, null=True)),
                ('children', models.ManyToManyField(related_name='parents', to='tasks.task')),
                ('queue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.queue')),
            ],
        ),
    ]
