# Generated by Django 5.2.4 on 2025-07-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_children_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='tasks.task'),
        ),
    ]
