# Generated by Django 5.2.4 on 2025-07-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='children',
        ),
        migrations.AddField(
            model_name='task',
            name='depencecies',
            field=models.ManyToManyField(blank=True, related_name='continuations', to='tasks.task'),
        ),
    ]
