# Generated by Django 5.2.4 on 2025-07-08 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_children_task_depencecies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.queue'),
        ),
    ]
