# Generated by Django 5.2.4 on 2025-07-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='queue',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
