# Generated by Django 5.2.4 on 2026-01-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_queue_delete_queue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='depencecies',
            new_name='dependencies',
        ),
    ]
